### ISSUE TITLE
FYI - TestResourceSet_WriteToEXE_NotEnd.golden reported as malicious by Norton

### ISSUE THREAD

**Issue by stefanjarina** [tc-hib/winres#1]
Hi,

just FYI. just encountered it.

today Norton 360 have identified this file as malicious.
https://github.com/tc-hib/winres/blob/master/testdata/TestResourceSet_WriteToEXE_NotEnd.golden

Category: Resolved Security Risks
Date & Time,Risk,Activity,Status,Recommended Action,Path - Filename
21.05.2022 21:23:13,High,TestResourceSet_WriteToEXE_NotEnd.golden (Heur.AdvML.L) detected by Auto-Protect,Quarantined,Resolved - No Action Required,G:\libs\go\pkg\mod\github.com\tc-hib\winres@v0.1.5\testdata\TestResourceSet_WriteToEXE_NotEnd.golden

https://www.virustotal.com/gui/file/0be0c845eecdc1dec55454ba39c44ade6e9ff26baaca01b81088af77a629b5d3/detection

**Comment by tc-hib** [comment]
Hi,

Thanks for telling me.
I'll have a look at it as soon as I can.

**Comment by GuilleAmutio** [comment]
+1

Just got notified that certains files are clasified as malicious.

![image](https://user-images.githubusercontent.com/56632305/181009014-6f0c0c92-513d-438d-8e02-95893bd7022c.png)

**Comment by tc-hib** [comment]
Thanks.
I think that might be normal, as I tried to test unusual layouts.
But I still have to find some time to have a closer look.

**Comment by Ahbrown41** [comment]
+1 to this issue McAfee is failing with the following:
![image](https://user-images.githubusercontent.com/5282718/197002363-b754314f-86f4-442d-8b37-b64b8bb3c855.png)

**Comment by rmariuzzo** [comment]
I tried to install this module as a dependency of wails and it was flagged as a malware.

**Comment by tc-hib** [comment]
I think I should separate the tests from the library.
